on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: MainTest
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Generate docs
      run: scripts/swag_init.sh
    - name: ApiTest
      run: go test -v internal/pkg/api/*
    - name: MainTest
      run: go test cmd/main_test.go -v -nodes=3 -posts=10 -timerange=5 -groups=5 -synctime=20
